spec:
  inputs:
    environment:
      type: string
      description: Deployment environment
      options: [Staging, Production]
      default: Staging
    check-run-id:
      type: number
      description: Check run ID previously created

---

stages:
  - deploy

workflow:
  rules:
    - if: $CI_PIPELINE_TRIGGERED
      when: always
    - when: never

deploy:
  environment: $[[ inputs.environment ]]
  stage: deploy
  timeout: 1h
  variables:  # Makes sure after_script runs to report timed out runs as failed.
    RUNNER_SCRIPT_TIMEOUT: 55m
    RUNNER_AFTER_SCRIPT_TIMEOUT: 5m
  before_script:
    - source .github/scripts/gitlab.sh
    - source .github/scripts/github.sh

    #region Installing system dependencies
    - section_start apk_add "Installing system dependencies"
    - apk add ansible openssh openssl jq curl
      # TODO: ansible collections (will need the docker one at the very least)
    - section_end apk_add
    #endregion

    #region Authenticating with GitHub
    - section_start gh_status_auth "Authenticating with GitHub"

    - echo "-----BEGIN RSA PRIVATE KEY-----" > /tmp/gh_rsa.pem
    - echo "$REMOTE_CI_APP_PRIVATE_KEY"     >> /tmp/gh_rsa.pem
    - echo "-----END RSA PRIVATE KEY-----"  >> /tmp/gh_rsa.pem

    - GH_JWT=$(generate_gh_app_jwt "$REMOTE_CI_APP_CLIENT_ID" /tmp/gh_rsa.pem)
    - GH_AUTH_TOKEN=$(authenticate_gh_app "$GH_JWT" "$REMOTE_CI_APP_INSTALL_ID")

      # Save token to disk so after_script can retrieve it.
      # Shell context won't be the same so environment variables will be reset.
    - echo -n "$GH_AUTH_TOKEN" > /tmp/auth_token

    - section_end gh_status_auth
    #endregion

    - section_start gh_status_start "Starting check run on GitHub"
    - start_check_run "$GH_AUTH_TOKEN" "$GITHUB_REPOSITORY" "$[[ inputs.check-run-id ]]"
    - section_end gh_status_start

  after_script:
    - source .github/scripts/gitlab.sh
    - source .github/scripts/github.sh
    - section_start gh_status_end "Completing check run on GitHub"
    - GH_AUTH_TOKEN=$(cat /tmp/auth_token)
    - if [ "$CI_JOB_STATUS" = "failed" ]; then conclusion="failure"; else conclusion="$CI_JOB_STATUS"; fi
    - finish_check_run "$GH_AUTH_TOKEN" "$GITHUB_REPOSITORY" $[[ inputs.check-run-id ]] "$conclusion"
    - section_end gh_status_end

  script:
    # TODO: real deploy script :>
    - echo 'Hello, CI!'
