services:
  elaastic-questions-db-8:
    image: mysql:8.3
    container_name: elaastic-questions-db-8
    environment:
      - MYSQL_USER=elaastic
      - MYSQL_DATABASE=elaastic-questions
      - MYSQL_PASSWORD=elaastic
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - "6683:3306"
    command: --character-set-server=utf8 --collation-server=utf8_general_ci
  elaastic-questions-db-test-8:
    image: mysql:8.3
    container_name: elaastic-questions-db-test-8
    environment:
      - MYSQL_USER=elaastic
      - MYSQL_DATABASE=elaastic-questions-test
      - MYSQL_PASSWORD=elaastic
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - "6684:3306"
    command: --character-set-server=utf8 --collation-server=utf8_general_ci
  cas:
    container_name: elaastic-cas
    build: docker-resources/cas
    ports:
      - "8443:8443"
  cas-2:
    container_name: elaastic-cas-2
    build: docker-resources/cas
    ports:
      - "8444:8443"

  auth-iam:
      image: quay.io/keycloak/keycloak:25.0.1
      command:
          - start-dev
          - --import-realm
      ports:
          - "8081:8080"
      volumes:
          - ./authentication/elaastic-iam/realms/:/opt/keycloak/data/import/
          - ./authentication/elaastic-iam/themes/:/opt/keycloak/themes/
      environment:
          KEYCLOAK_ADMIN: admin
          KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
          KC_HTTP_PORT: 8080
          KC_HOSTNAME_URL: http://host.docker.internal:8081
          KC_HOSTNAME_ADMIN_URL: http://host.docker.internal:8081
          KC_HOSTNAME_STRICT_BACKCHANNEL: true
          KC_HTTP_RELATIVE_PATH: /
          KC_HTTP_ENABLED: true
          KC_HEALTH_ENABLED: true
          KC_METRICS_ENABLED: true
      extra_hosts:
          - "host.docker.internal:host-gateway"
      healthcheck:
          test: [ 'CMD-SHELL', '[ -f /tmp/HealthCheck.java ] || echo "public class HealthCheck { public static void main(String[] args) throws java.lang.Throwable { System.exit(java.net.HttpURLConnection.HTTP_OK == ((java.net.HttpURLConnection)new java.net.URL(args[0]).openConnection()).getResponseCode() ? 0 : 1); } }" > /tmp/HealthCheck.java && java /tmp/HealthCheck.java http://localhost:8080/auth/health/live' ]
          interval: 5s
          timeout: 5s
          retries: 20

  auth-idp-saml2:
      image: quay.io/keycloak/keycloak:25.0.1
      command:
          - start-dev
          - --import-realm
      ports:
          - "8082:8080"
      volumes:
          - ./authentication/idp-saml2/realms/:/opt/keycloak/data/import/
      environment:
          KEYCLOAK_ADMIN: admin
          KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
          KC_HTTP_PORT: 8080
          KC_HOSTNAME_URL: http://host.docker.internal:8082
          KC_HOSTNAME_ADMIN_URL: http://host.docker.internal:8082
          KC_HOSTNAME_STRICT_BACKCHANNEL: true
          KC_HTTP_RELATIVE_PATH: /
          KC_HTTP_ENABLED: true
          KC_HEALTH_ENABLED: true
          KC_METRICS_ENABLED: true
      extra_hosts:
          - "host.docker.internal:host-gateway"
      healthcheck:
          test: [ 'CMD-SHELL', '[ -f /tmp/HealthCheck.java ] || echo "public class HealthCheck { public static void main(String[] args) throws java.lang.Throwable { System.exit(java.net.HttpURLConnection.HTTP_OK == ((java.net.HttpURLConnection)new java.net.URL(args[0]).openConnection()).getResponseCode() ? 0 : 1); } }" > /tmp/HealthCheck.java && java /tmp/HealthCheck.java http://localhost:8080/auth/health/live' ]
          interval: 5s
          timeout: 5s
          retries: 20