services:
  elaastic-questions-db-8:
    image: mysql:8.3
    container_name: elaastic-questions-db-8
    environment:
      - MYSQL_USER=elaastic
      - MYSQL_DATABASE=elaastic-questions
      - MYSQL_PASSWORD=elaastic
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - "6683:3306"
    command: --character-set-server=utf8 --collation-server=utf8_general_ci
  elaastic-questions-db-test-8:
    image: mysql:8.3
    container_name: elaastic-questions-db-test-8
    environment:
      - MYSQL_USER=elaastic
      - MYSQL_DATABASE=elaastic-questions-test
      - MYSQL_PASSWORD=elaastic
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - "6684:3306"
    command: --character-set-server=utf8 --collation-server=utf8_general_ci
  cas:
    container_name: elaastic-cas
    build: docker-resources/cas
    ports:
      - "8443:8443"
  cas-2:
    container_name: elaastic-cas-2
    build: docker-resources/cas
    ports:
      - "8444:8443"
  mailHog:
    container_name: elaastic-mailhog
    image: mailhog/mailhog
    labels:
      - "traefik.enable=true"
      # Configuration for web interface
      - "traefik.http.routers.mailhog.rule=Host(`mailhog.local`)"
      - "traefik.http.services.mailhog.loadbalancer.server.port=8025"
      - "traefik.http.routers.mailhog.entrypoints=web"
      # Configuration for SMTP server
      - "traefik.tcp.routers.mailhog-smtp.rule=HostSNI(`*`)"
      - "traefik.tcp.routers.mailhog-smtp.entrypoints=smtp"
      - "traefik.tcp.routers.mailhog-smtp.service=mailhog-smtp"
      - "traefik.tcp.services.mailhog-smtp.loadbalancer.server.port=1025"

  auth-iam:
      image: quay.io/keycloak/keycloak:25.0.6
      command:
          - start-dev
          - --import-realm
      labels:
          - "traefik.enable=true"
          - "traefik.http.routers.auth-iam.rule=Host(`iam.local`)"
          - "traefik.http.services.auth-iam.loadbalancer.server.port=80"
          - "traefik.http.routers.auth-iam.entrypoints=web"
      networks:
          default:
              aliases:
                  - iam.local
      volumes:
          - ./authentication/elaastic-iam/realms/:/opt/keycloak/data/import/
          - ./authentication/elaastic-iam/themes/:/opt/keycloak/themes/
      environment:
          KEYCLOAK_ADMIN: admin
          KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
          #KC_PROXY: 'edge'
          KC_HTTP_PORT: 80
          KC_HOSTNAME_URL: http://iam.local
          KC_HOSTNAME_ADMIN_URL: http://iam.local
          KC_HOSTNAME_STRICT_BACKCHANNEL: true
          KC_HTTP_RELATIVE_PATH: /
          KC_HTTP_ENABLED: true
          KC_HEALTH_ENABLED: true
          KC_METRICS_ENABLED: true

  auth-idp-saml2:
      image: quay.io/keycloak/keycloak:25.0.6
      command:
          - start-dev
          - --import-realm
      labels:
          - "traefik.enable=true"
          - "traefik.http.routers.idp.rule=Host(`idp.local`)"
          - "traefik.http.services.idp.loadbalancer.server.port=80"
          - "traefik.http.routers.idp.entrypoints=web"
      networks:
          default:
              aliases:
                    - idp.local
      volumes:
          - ./authentication/idp-saml2/realms/:/opt/keycloak/data/import/
      environment:
          KEYCLOAK_ADMIN: admin
          KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
          KC_HTTP_PORT: 80
          KC_HOSTNAME_URL: http://idp.local
          KC_HOSTNAME_ADMIN_URL: http://idp.local
          KC_HOSTNAME_STRICT_BACKCHANNEL: true
          KC_HTTP_RELATIVE_PATH: /
          KC_HTTP_ENABLED: true
          KC_HEALTH_ENABLED: true
          KC_METRICS_ENABLED: true

  traefik:
      image: traefik:v3.4
      command:
          - --api.dashboard=true
          - --providers.docker=true
          - --providers.docker.exposedbydefault=false
          - --entrypoints.web.address=:80
          - --entrypoints.smtp.address=:1025
          - --log.level=DEBUG

      ports:
          - "80:80"
          - "1025:1025"
      volumes:
          - /var/run/docker.sock:/var/run/docker.sock:ro
      labels:
          - "traefik.enable=true"
          - "traefik.http.routers.dashboard.rule=Host(`traefik.localhost`)"
          - "traefik.http.routers.dashboard.service=api@internal"
          - "traefik.http.services.dashboard.loadbalancer.server.port=8080"