# Debug Spring security
logging.level.org.springframework.security=TRACE
logging.level.org.elaastic.questions.directory.cas=TRACE

# Mail configuration
spring.mail.host=localhost
spring.mail.port=1025
spring.mail.username=
spring.mail.password=
spring.mail.protocol=smtp
spring.mail.defaultEncoding=UTF-8