# Debug Spring security
logging.level.org.springframework.security=TRACE
logging.level.org.elaastic.questions.directory.cas=TRACE

# Mail configuration
spring.mail.host=localhost
spring.mail.port=1025
spring.mail.username=
spring.mail.password=
spring.mail.protocol=smtp
spring.mail.defaultEncoding=UTF-8

# For activating OIDC authentication:
# - Set elaastic.openid.enabled to true
# - Uncomment the spring.security.oauth2.client.* lines below
# - Launch the IAM server (see README.md)
elaastic.openid.enabled = false
#spring.security.oauth2.client.provider.elaastic-keycloak.issuer-uri=http://iam.local/realms/elaastic-keycloak
#spring.security.oauth2.client.registration.keycloak.provider=elaastic-keycloak
#spring.security.oauth2.client.registration.keycloak.authorization-grant-type=authorization_code
#spring.security.oauth2.client.registration.keycloak.client-id=elaastic
#spring.security.oauth2.client.registration.keycloak.client-secret=secret
#spring.security.oauth2.client.registration.keycloak.scope=openid
