package org.elaastic.questions.onboarding


enum class OnboardingChapter(val propertyString: String, val i18nMessages: List<String>) {
    COURSE_PAGE(
        "course_page",
        listOf(
            "onboarding.introduction.title",
            "onboarding.introduction.content",
            "onboarding.content.course_creation.1",
            "onboarding.content.course_creation.2",
            "onboarding.content.course_creation.3"
        )
    ),
    COURSE_CREATION_PAGE(
            "course_creation_page",
            listOf(
                "onboarding.content.course_creation.4",
                "onboarding.content.course_creation.5")
            ),
    SUBJECT_PAGE(
            "subject_page",
            listOf(
                "onboarding.content.subject_creation.1",
                "onboarding.content.subject_creation.2",
                "onboarding.content.subject_creation.3")
            ),
    SUBJECT_CREATION_PAGE(
            "subject_creation_page",
            listOf(
                "onboarding.content.subject_creation.4",
                "onboarding.content.subject_creation.5",
                "onboarding.content.subject_creation.6")
            ),
    SUBJECT_EDITION_PAGE(
            "subject_edition_page",
            listOf(
                "onboarding.content.subject_creation.7",
                "onboarding.content.subject_creation.8",
                "onboarding.content.subject_creation.9",
                "onboarding.content.subject_creation.10",
                "onboarding.content.subject_creation.11",
                "onboarding.content.question_creation.2",
                "onboarding.content.question_creation.15",
                "onboarding.content.question_creation.16",
                "onboarding.content.question_creation.17",
                "onboarding.content.question_creation.18",
                "onboarding.content.assignment_creation.1",
                "onboarding.content.assignment_creation.2",
                "onboarding.content.assignment_creation.3",
                "onboarding.content.assignment_creation.9",
                "onboarding.content.assignment_creation.10",
                "onboarding.content.assignment_creation.11",
                "onboarding.content.assignment_creation.12")
            ),
    QUESTION_CREATION_PAGE(
            "question_creation_page",
            listOf(
                "onboarding.content.question_creation.3",
                "onboarding.content.question_creation.4",
                "onboarding.content.question_creation.5",
                "onboarding.content.question_creation.6",
                "onboarding.content.question_creation.7",
                "onboarding.content.question_creation.8",
                "onboarding.content.question_creation.9",
                "onboarding.content.question_creation.10",
                "onboarding.content.question_creation.14")
            ),
    ASSIGNMENT_CREATION_PAGE(
            "assignment_creation_page",
            listOf("onboarding.content.assignment_creation.4",
                    "onboarding.content.assignment_creation.5",
                    "onboarding.content.assignment_creation.6",
                    "onboarding.content.assignment_creation.7",
                    "onboarding.content.assignment_creation.8")),
    PLAYER_PAGE(
            "player_page",
            listOf("onboarding.content.prepare_sequence.1",
                    "onboarding.content.prepare_sequence.2",
                    "onboarding.content.prepare_sequence.3",
                    "onboarding.content.prepare_sequence.4",
                    "onboarding.content.play_sequence.1",
                    "onboarding.content.play_sequence.2",
                    "onboarding.content.play_sequence.3",
                    "onboarding.content.play_sequence.4")
            ),
    SHARED_SUBJECTS_PAGE(
            "shared_subjects_page",
            listOf("onboarding.content.shared_subjects.1",
                    "onboarding.content.shared_subjects.2",
                    "onboarding.content.shared_subjects.3")),
    ONE_SHARED_SUBJECT_PAGE(
            "one_shared_subject_page",
            listOf("onboarding.content.one_shared_subject.1",
                    "onboarding.content.one_shared_subject.2",
                    "onboarding.content.one_shared_subject.3"));

    companion object {
        fun from(findValue: String): OnboardingChapter = values().first { it.propertyString == findValue }
    }
}