all:
  hosts:
    irit_vm:
      ansible_ssh_user: "{{ lookup('env', 'SSH_USER') }}"
      ansible_ssh_port: "{{ lookup('env', 'SSH_PORT') }}"
      ansible_ssh_host: "{{ lookup('env', 'SSH_HOST') }}"
      ansible_ssh_private_key_file: "~/.ssh/id_ed25519"

  vars:
    ansible_ssh_extra_args: "-o IdentitiesOnly=yes"
