FROM tomcat:9.0.35-jdk11
ADD tomcat-users.xml /usr/local/tomcat/conf/tomcat-users.xml
ADD manager-context.xml /usr/local/tomcat/webapps/manager/META-INF/context.xml
ADD elaastic-questions.properties /usr/local/tomcat/conf/elaastic-questions.properties
ADD elaastic-questions-context.xml /usr/local/tomcat/conf/Catalina/localhost/elaastic-questions.xml
