name: "Chromatic"

on:
  pull_request:
    branches: [ develop ]
    types: [opened, synchronize, reopened]

jobs:
  chromatic:
    name: Run Chromatic
    runs-on: ubuntu-latest
    defaults:
        run:
            working-directory: ./ui-components
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: 22.12.0
      - name: Install dependencies
        run: npm install
      - name: Run Chromatic
        uses: chromaui/action@latest
        with:
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
          workingDir: ./ui-components